version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 8080:3000
      - 9229:9229
    volumes:
      - ./frontend/node_modules:/usr/src/frontend/node_modules
      - ./frontend/.next:/usr/src/frontend/.next
      - ./frontend:/usr/src/frontend
