version: "3"

services:
  postgres:
    container_name: postgres
    image: postgres
    env_file: .env
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - server-net
    restart: always
    volumes:
      - ./volumes/postgres-data:/var/lib/postgresql/data

networks:
  server-net:
    driver: bridge
